from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from datetime import datetime


def generate_water_quality_report(
    report_type="Water Quality Summary",
    time_range="Last 7 Days",
    start_date="",
    end_date="",
    data_source="All Sources",
):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    heading = styles["Heading2"]
    normal = styles["Normal"]

    elements = []

    # Title
    elements.append(
    Paragraph(f"Report Type: {report_type}", normal)
    )

    elements.append(
    Paragraph(f"Time Range: {time_range}", normal)
    )

    if start_date and end_date:
        elements.append(
        Paragraph(
            f"Period: {start_date} to {end_date}",
            normal,
        )
    )
    elements.append(
    Paragraph(f"Data Source: {data_source}", normal)
    )

    elements.append(Spacer(1, 20))

    # Summary
    elements.append(
        Paragraph("Water Quality Summary", heading)
    )

    summary_data = [
        ["Metric", "Value"],
        ["Overall Water Safety Score", "94 / 100"],
        ["Tests Conducted", "1248"],
        ["Alerts Triggered", "23"],
        ["Data Uptime", "99.7%"],
    ]

    summary_table = Table(
        summary_data,
        colWidths=[280, 150],
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(summary_table)

    elements.append(Spacer(1, 20))

    # Contaminants
    elements.append(
        Paragraph("Contaminant Analysis", heading)
    )

    contaminant_data = [
        ["Parameter", "Value", "Safe Limit", "Status"],
        ["Arsenic", "0.006 mg/L", "0.01 mg/L", "Safe"],
        ["Lead", "0.004 mg/L", "0.01 mg/L", "Safe"],
        ["Iron", "0.18 mg/L", "0.30 mg/L", "Safe"],
        ["Manganese", "0.08 mg/L", "0.10 mg/L", "Safe"],
        ["Chromium", "0.03 mg/L", "0.05 mg/L", "Safe"],
    ]

    contaminant_table = Table(
        contaminant_data,
        colWidths=[120, 120, 120, 80],
    )

    contaminant_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(contaminant_table)

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "This report is generated by the Toyam Water Monitoring System.",
            normal,
        )
    )

    doc.build(elements)

    buffer.seek(0)

    return buffer