from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from datetime import datetime


def generate_water_quality_report(
    summary=None,
    contaminants=None,
    trends=None,
    heatmap=None,
    report_type="Water Quality Summary",
    time_range="Last 7 Days",
    start_date="",
    end_date="",
    data_source="All Sources",
    **kwargs
):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()

    title = styles["Title"]
    heading = styles["Heading2"]
    normal = styles["Normal"]

    elements = []

    # Title
    elements.append(
        Paragraph(f"Report Type: {report_type}", normal)
    )

    elements.append(
        Paragraph(f"Time Range: {time_range}", normal)
    )

    if start_date and end_date:
        elements.append(
            Paragraph(
                f"Period: {start_date} to {end_date}",
                normal,
            )
        )
    elements.append(
        Paragraph(f"Data Source: {data_source}", normal)
    )

    elements.append(Spacer(1, 20))

    # Summary
    elements.append(
        Paragraph("Water Quality Summary", heading)
    )

    summary_data = [["Metric", "Value"]]
    if summary:
        summary_data.append(["Overall Water Safety Score", f"{summary.get('overall_water_safety_score', '--')} / 100"])
        summary_data.append(["Tests Conducted", str(summary.get("tests_conducted", "--"))])
        summary_data.append(["Alerts Triggered", str(summary.get("alerts_triggered", "--"))])
        summary_data.append(["Data Uptime", f"{summary.get('data_uptime', '--')}%"])
    else:
        summary_data.extend([
            ["Overall Water Safety Score", "94 / 100"],
            ["Tests Conducted", "1248"],
            ["Alerts Triggered", "23"],
            ["Data Uptime", "99.7%"],
        ])

    summary_table = Table(
        summary_data,
        colWidths=[280, 150],
    )

    summary_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.black),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(summary_table)

    elements.append(Spacer(1, 20))

    # Contaminants
    elements.append(
        Paragraph("Contaminant Analysis", heading)
    )

    contaminant_data = [["Parameter", "Value", "Safe Limit", "Status"]]
    if contaminants:
        for c in contaminants:
            v = str(c.get("value", "") or c.get("raw_value", ""))
            u = str(c.get("unit", ""))
            if u and u not in v:
                v = f"{v} {u}"
            s_lim = str(c.get("safe_limit", ""))
            if u and u not in s_lim:
                s_lim = f"{s_lim} {u}"
            contaminant_data.append([
                str(c.get("parameter", "")),
                v.strip(),
                s_lim.strip(),
                str(c.get("status", "")),
            ])
    else:
        contaminant_data.extend([
            ["Arsenic", "0.006 mg/L", "0.01 mg/L", "Safe"],
            ["Lead", "0.004 mg/L", "0.01 mg/L", "Safe"],
            ["Iron", "0.18 mg/L", "0.30 mg/L", "Safe"],
            ["Manganese", "0.08 mg/L", "0.10 mg/L", "Safe"],
            ["Chromium", "0.03 mg/L", "0.05 mg/L", "Safe"],
        ])

    contaminant_table = Table(
        contaminant_data,
        colWidths=[120, 120, 120, 80],
    )

    contaminant_table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("PADDING", (0, 0), (-1, -1), 8),
        ])
    )

    elements.append(contaminant_table)


    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "This report is generated by the Toyam Water Monitoring System.",
            normal,
        )
    )

    doc.build(elements)

    buffer.seek(0)

    return buffer


def generate_statewide_executive_summary_report(
    statewide_data=None,
    report_type="Statewide Executive Summary",
    time_range="Last 7 Days",
    start_date="",
    end_date="",
    data_source="All Sources",
    **kwargs
):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    normal = styles["Normal"]
    heading = styles["Heading2"]
    title_style = styles["Title"]

    elements = []

    # Title Banner
    elements.append(Paragraph("<b>TOYAM // JHARKHAND WATER MONITORING PORTAL</b>", title_style))
    elements.append(Paragraph(f"<b>Report Type:</b> {report_type}", normal))
    elements.append(Paragraph(f"<b>Time Range:</b> {time_range} | <b>Data Source:</b> {data_source}", normal))
    if start_date and end_date:
        elements.append(Paragraph(f"<b>Period:</b> {start_date} to {end_date}", normal))
    elements.append(Paragraph(f"<b>Generated:</b> {datetime.now().strftime('%Y-%m-%d %H:%M:%S IST')}", normal))
    elements.append(Spacer(1, 15))

    # 1. Statewide Key Performance Indicators Table
    elements.append(Paragraph("Statewide Water Infrastructure KPIs", heading))
    elements.append(Spacer(1, 6))

    kpis_data = [["KPI Metric", "Recorded Value", "Status / Standard"]]

    kpis_list = statewide_data.get("kpis", []) if statewide_data else []
    if kpis_list:
        for k in kpis_list:
            lbl = k.get("label", k.get("key", ""))
            val = f"{k.get('value', '')} {k.get('unit', '')}".strip()
            sub = k.get("baseline_comparison") or k.get("compliance_standard") or k.get("district_types") or ""
            if k.get("key") == "units":
                sub = f"{k.get('in_maintenance_count', 3)} IN CUTOFF"
            elif k.get("key") == "incursions":
                sub = k.get("status_badge", "AUTO-CUTOFF ENGAGED")
            kpis_data.append([lbl, val, sub])
    else:
        kpis_data.extend([
            ["Overall Compliance Index", "94.2 % INDEX", "BIS IS 10500 Compliant"],
            ["Purification Units", "40/45 ONLINE", "5 IN CUTOFF (Dhanbad, Ramgarh, Hazaribagh)"],
            ["Incursions Blocked", "18 EVENTS", "AUTO-CUTOFF ENGAGED"],
            ["Population Protected", "384,200 SOULS", "14 Mining & Rural Districts"],
            ["Total Clean Water Dispensed", "1,482,900 L", "+8.4% vs 30d baseline"],
        ])

    kpi_table = Table(kpis_data, colWidths=[200, 140, 180])
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(kpi_table)
    elements.append(Spacer(1, 15))

    # 2. Contaminants Table
    elements.append(Paragraph("Heavy Metal & Contaminant Spectral Surveillance (BIS IS 10500)", heading))
    elements.append(Spacer(1, 6))

    contam_data = [["Contaminant", "Recorded Avg", "Max Ceiling", "Status / Note"]]
    contams = statewide_data.get("heavy_metal_contaminants", []) if statewide_data else []
    if contams:
        for c in contams:
            lbl = c.get("label", c.get("key", ""))
            val = f"{c.get('value', 0):.3f} ppm"
            ceil = f"{c.get('ceiling', 0):.3f} ppm"
            note = c.get("note", "Safe")
            contam_data.append([lbl, val, ceil, note])
    else:
        contam_data.extend([
            ["LEAD (PB)", "0.018 ppm", "0.010 ppm", "+80% above safe limit"],
            ["ARSENIC (AS)", "0.004 ppm", "0.010 ppm", "Safe parameters"],
            ["FLUORIDE (F-)", "0.820 ppm", "1.000 ppm", "Elevated in Palamu belt"],
            ["CHROMIUM (CR+6)", "0.012 ppm", "0.050 ppm", "Trace levels only"],
            ["IRON (FE)", "0.340 ppm", "0.300 ppm", "Filtration backwash req."],
        ])

    contam_table = Table(contam_data, colWidths=[150, 110, 110, 150])
    contam_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(contam_table)
    elements.append(Spacer(1, 15))

    # 3. Fleet Overview Summary
    elements.append(Paragraph("Statewide Plant Fleet Status Breakdown", heading))
    elements.append(Spacer(1, 6))

    counts = statewide_data.get("status_counts", {}) if statewide_data else {"all": 45, "normal": 40, "alert": 2, "cutoff": 3}
    tot_cnt = counts.get("all", 45) or 45
    norm_cnt = counts.get("normal", 40)
    alt_cnt = counts.get("alert", 2)
    cut_cnt = counts.get("cutoff", 3)

    fleet_summary_data = [
        ["Classification", "Count", "Percentage", "Operational Action Required"],
        ["Safe Potability (Normal)", str(norm_cnt), f"{norm_cnt/tot_cnt*100:.1f}%", "Routine monitoring"],
        ["Warning / Heavy TDS (Alert)", str(alt_cnt), f"{alt_cnt/tot_cnt*100:.1f}%", "Filter backwash & secondary audit"],
        ["Critical Contamination (Cutoff)", str(cut_cnt), f"{cut_cnt/tot_cnt*100:.1f}%", "Auto-Solenoid Shutoff active, field team dispatched"],
        ["Total Active Monitored Probes", str(tot_cnt), "100.0%", "Continuous telemetry stream"],
    ]

    fleet_table = Table(fleet_summary_data, colWidths=[150, 60, 80, 230])
    fleet_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(fleet_table)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("This executive report is generated by the Toyam SCADA & Statewide Water Quality Monitoring System.", normal))

    doc.build(elements)
    buffer.seek(0)
    return buffer